make valgrind more generic

diff --git a/.github/workflows/valgrind.yaml b/.github/workflows/valgrind.yaml
--- a/.github/workflows/valgrind.yaml
+++ b/.github/workflows/valgrind.yaml
@@ -34,22 +34,31 @@ jobs:
       - name: Build
         run: cmake --build build --config ${{ env.BUILD_TYPE }} -j$(nproc)
 
-      - name: Run tests with Valgrind
+      - name: Run Valgrind on test executables
         run: |
           cd build
-          valgrind --tool=memcheck \
-                   --leak-check=full \
-                   --show-leak-kinds=all \
-                   --track-origins=yes \
-                   --verbose \
-                   --error-exitcode=1 \
-                   --gen-suppressions=all \
-                   --suppressions=../valgrind_suppressions.txt \
-                   ./TradingTests
-        continue-on-error: true
+          for test_executable in $(find . -type f -executable -name '*Tests'); do
+            echo "Running Valgrind on $test_executable"
+            valgrind --tool=memcheck \
+                     --leak-check=full \
+                     --show-leak-kinds=all \
+                     --track-origins=yes \
+                     --verbose \
+                     --error-exitcode=1 \
+                     --gen-suppressions=all \
+                     --suppressions=../valgrind_suppressions.txt \
+                     --log-file=valgrind_${test_executable##*/}.log \
+                     $test_executable
+            if [ $? -ne 0 ]; then
+              echo "Valgrind detected errors in $test_executable"
+              exit_code=1
+            fi
+          done
+          exit ${exit_code:-0}
 
       - name: Upload Valgrind logs
         uses: actions/upload-artifact@v3
+        if: always()
         with:
           name: valgrind-logs
-          path: build/valgrind.log
+          path: build/valgrind_*.log
